# Generated by Django 4.2.9 on 2024-01-09 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_pages_alter_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pages',
            options={'verbose_name': 'page', 'verbose_name_plural': 'pages'},
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='category_name',
            new_name='subcategory_name',
        ),
    ]
