# Generated by Django 4.2.9 on 2024-01-11 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_product_parent_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='parent_category',
        ),
    ]
