# Generated by Django 4.2.9 on 2024-01-12 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0021_remove_cartitem_is_active_cartitem_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variations',
            options={'verbose_name': 'variation', 'verbose_name_plural': 'variations'},
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
    ]
